import type {Metadata} from "next";
import "./globals.css";
import {AppRouterCacheProvider} from "@mui/material-nextjs/v13-appRouter";
import {ReactQueryClientProvider} from "@/components/ReactQueryClientProvider";


export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({children,}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <ReactQueryClientProvider>
            <html lang="en">
            <body>
                <AppRouterCacheProvider options={{enableCssLayer: true}}>{children}</AppRouterCacheProvider></body>
            </html>
        </ReactQueryClientProvider>
    );
}
